pub mod config;
pub mod population;
pub mod genome;
pub mod errors;
pub mod gene;
pub mod connection_gene;
mod species;
mod innovation_number;
pub(crate) mod activation;
pub(crate) mod aggregation;
mod attribute;
mod math;
